-- Create dev schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS dev;

-- Grant privileges to admin user
GRANT ALL PRIVILEGES ON SCHEMA dev TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA dev TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA dev TO admin;

-- Set default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA dev GRANT ALL ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA dev GRANT ALL ON SEQUENCES TO admin;

